from tkinter import *
from PIL import ImageTk, Image
import random
root=Tk()
root.title("Endless Pokemon Game")
root.geometry("500x500")
squirtle = ImageTk.PhotoImage(Image.open("squirtle.jpg"))
ratata = ImageTk.PhotoImage(Image.open("ratata.jpg"))
pikachu = ImageTk.PhotoImage(Image.open("pikachu.jpg"))
persion = ImageTk.PhotoImage(Image.open("persion.jpg"))
paras = ImageTk.PhotoImage(Image.open("paras.jpg"))
nidoking = ImageTk.PhotoImage(Image.open("nidoking.jpg"))
meowth = ImageTk.PhotoImage(Image.open("meowth.jpg"))
kadabra = ImageTk.PhotoImage(Image.open("kadabra.jpg"))
jigglypuff = ImageTk.PhotoImage(Image.open("jigglypuff.jpg"))
lyvasour = ImageTk.PhotoImage(Image.open("Iyvasour.jpg"))
charmender = ImageTk.PhotoImage(Image.open("charmender.jpg"))
bulbasour = ImageTk.PhotoImage(Image.open("bulbasour.jpg"))
abra = ImageTk.PhotoImage(Image.open("abra.jpg"))
cardimage=Label(root)
cardimage.place(relx=0.5, rely=0.5, anchor=CENTER)
player1label=Label(root, text="Player 1")
player1label.place(relx=0.1, rely=0.1, anchor=CENTER)
player2label=Label(root, text="Player 2")
player2label.place(relx=0.9, rely=0.1, anchor=CENTER)
player1scorelabel=Label(root, text="Player 1's score: ")
player1scorelabel.place(relx=0.1, rely=0.2, anchor=CENTER)
player2scorelabel=Label(root, text="Player 2's score: ")
player2scorelabel.place(relx=0.9, rely=0.2, anchor=CENTER)
root.mainloop()